// IPC channel definitions — typed bridge between renderer and main
export const IPC = {
  GET_PAIRING_TOKEN: "bridge:get-pairing-token",
  GET_SESSIONS: "bridge:get-sessions",
  GET_CONNECTION_COUNT: "bridge:get-connection-count",
  CAPTURE_SCREENSHOT: "capture:screenshot",
  GET_ACTIVE_CAPTURE_CONTEXT: "capture:get-active-context",
  SET_ACTIVE_CAPTURE_CONTEXT: "capture:set-active-context",
  EXPORT_BUG: "bug:export",
  SEND_COMMAND: "agent:send-command",
  EXECUTE_AGENT_COMMAND: "agent:execute-command",
  GET_EVENTS: "session:get-events",
  SAVE_BUG_REPORT: "bug:save",
  GET_BUG_REPORTS: "bug:get-all",
  DELETE_BUG_REPORT: "bug:delete",
  SAVE_VIDEO: "video:save",
  REVEAL_FILE: "file:reveal",
  GET_PROJECTS: "project:get-all",
  CREATE_PROJECT: "project:create",
  UPDATE_PROJECT: "project:update",
  DELETE_PROJECT: "project:delete",
  GET_TICKETS: "ticket:get-all",
  CREATE_TICKET: "ticket:create",
  UPDATE_TICKET: "ticket:update",
  DELETE_TICKET: "ticket:delete",
  GET_MEDIA: "media:get-all",
  ATTACH_MEDIA_TO_BUG: "media:attach-to-bug",
  DETACH_MEDIA_FROM_BUG: "media:detach-from-bug",
  // Push (main→renderer) channel names
  SESSION_EVENT: "session:event",
  SESSION_VIDEO_PROGRESS: "session:video-progress",
  SESSION_VIDEO_SAVED: "session:video-saved",
  BRIDGE_CONNECTION_CHANGE: "bridge:connection-change",
} as const;
